///////////////////////////////////////////////////
// This file is generated by build-interfaces.js //
///////////////////////////////////////////////////
/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable @typescript-eslint/no-duplicate-type-constituents */
import { LaraJoinPoint, registerJoinpointMapper, wrapJoinPoint, unwrapJoinPoint, } from "lara-js/api/LaraJoinPoint.js";
export class Joinpoint extends LaraJoinPoint {
    /**
     * String representation of the ast
     */
    get ast() {
        return wrapJoinPoint(this._javaObject.getAst());
    }
    /**
     * Returns an array with the children of the node, ignoring null nodes
     */
    get children() {
        return wrapJoinPoint(this._javaObject.getChildren());
    }
    /**
     * String with the code represented by this node
     */
    get code() {
        return wrapJoinPoint(this._javaObject.getCode());
    }
    /**
     * Retrieves all descendants of the join point
     */
    get descendants() {
        return wrapJoinPoint(this._javaObject.getDescendants());
    }
    /**
     * The id of the node
     */
    get id() {
        return wrapJoinPoint(this._javaObject.getId());
    }
    /**
     * Returns the parent node in the AST, or undefined if it is the root node
     */
    get parent() {
        return wrapJoinPoint(this._javaObject.getParent());
    }
    /**
     * Returns the 'program' joinpoint
     */
    get root() {
        return wrapJoinPoint(this._javaObject.getRoot());
    }
    /**
     * Looks for an ancestor joinpoint name, walking back on the AST
     */
    getAncestor(type) {
        return wrapJoinPoint(this._javaObject.getAncestor(unwrapJoinPoint(type)));
    }
    /**
     * Returns the child of the node at the given index, ignoring null nodes
     */
    getChild(index) {
        return wrapJoinPoint(this._javaObject.getChild(unwrapJoinPoint(index)));
    }
    /**
     * Retrieves the descendants of the given type
     */
    getDescendants(type) {
        return wrapJoinPoint(this._javaObject.getDescendants(unwrapJoinPoint(type)));
    }
    /**
     * Retrieves the descendants of the given type, including the node itself
     */
    getDescendantsAndSelf(type) {
        return wrapJoinPoint(this._javaObject.getDescendantsAndSelf(unwrapJoinPoint(type)));
    }
    /**
     * Removes the node associated to this joinpoint from the AST
     */
    detach() {
        return wrapJoinPoint(this._javaObject.detach());
    }
    /**
     * Inserts the given join point after this join point
     */
    insertAfter(p1) {
        return wrapJoinPoint(this._javaObject.insertAfter(unwrapJoinPoint(p1)));
    }
    /**
     * Inserts the given join point before this join point
     */
    insertBefore(p1) {
        return wrapJoinPoint(this._javaObject.insertBefore(unwrapJoinPoint(p1)));
    }
    /**
     * Replaces this node with the given node
     */
    replaceWith(p1) {
        return wrapJoinPoint(this._javaObject.replaceWith(unwrapJoinPoint(p1)));
    }
    /**
     * Overload which accepts a list of strings
     */
    replaceWithStrings(node) {
        return wrapJoinPoint(this._javaObject.replaceWithStrings(unwrapJoinPoint(node)));
    }
}
/**
 * Class definition
 */
export class ClassNode extends Joinpoint {
    get classDescriptor() {
        return wrapJoinPoint(this._javaObject.getClassDescriptor());
    }
    get fields() {
        return wrapJoinPoint(this._javaObject.getFields());
    }
    get methods() {
        return wrapJoinPoint(this._javaObject.getMethods());
    }
    get superClassDescriptor() {
        return wrapJoinPoint(this._javaObject.getSuperClassDescriptor());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Expression
 */
export class Expression extends Joinpoint {
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Field definition
 */
export class FieldNode extends Joinpoint {
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Field reference
 */
export class FieldReference extends Expression {
}
/**
 * Label reference
 */
export class LabelReference extends Expression {
    get decl() {
        return wrapJoinPoint(this._javaObject.getDecl());
    }
}
/**
 * Literal
 */
export class Literal extends Expression {
}
/**
 * The application's manifest
 */
export class Manifest extends Joinpoint {
    get activities() {
        return wrapJoinPoint(this._javaObject.getActivities());
    }
    get packageName() {
        return wrapJoinPoint(this._javaObject.getPackageName());
    }
    get services() {
        return wrapJoinPoint(this._javaObject.getServices());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Method definition
 */
export class MethodNode extends Joinpoint {
    get isStatic() {
        return wrapJoinPoint(this._javaObject.getIsStatic());
    }
    get name() {
        return wrapJoinPoint(this._javaObject.getName());
    }
    get prototype() {
        return wrapJoinPoint(this._javaObject.getPrototype());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Method prototype
 */
export class MethodPrototype extends Literal {
    get parameters() {
        return wrapJoinPoint(this._javaObject.getParameters());
    }
    get returnType() {
        return wrapJoinPoint(this._javaObject.getReturnType());
    }
}
/**
 * Method reference
 */
export class MethodReference extends Expression {
    get name() {
        return wrapJoinPoint(this._javaObject.getName());
    }
    get parentClassDescriptor() {
        return wrapJoinPoint(this._javaObject.getParentClassDescriptor());
    }
    get prototype() {
        return wrapJoinPoint(this._javaObject.getPrototype());
    }
}
/**
 * Placeholder node
 */
export class Placeholder extends Joinpoint {
    get kind() {
        return wrapJoinPoint(this._javaObject.getKind());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * App node
 */
export class Program extends Joinpoint {
    get classes() {
        return wrapJoinPoint(this._javaObject.getClasses());
    }
    get manifest() {
        return wrapJoinPoint(this._javaObject.getManifest());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Register list
 */
export class RegisterList extends Expression {
}
/**
 * Register range
 */
export class RegisterRange extends Expression {
}
/**
 * Register reference
 */
export class RegisterReference extends Expression {
}
/**
 * Resource nodes, like xml files are not being handled for now
 */
export class ResourceNode extends Joinpoint {
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Sparse switch element
 */
export class SparseSwitchElement extends Expression {
    get label() {
        return wrapJoinPoint(this._javaObject.getLabel());
    }
}
/**
 * Statement
 */
export class Statement extends Joinpoint {
    get nextStatement() {
        return wrapJoinPoint(this._javaObject.getNextStatement());
    }
    get prevStatement() {
        return wrapJoinPoint(this._javaObject.getPrevStatement());
    }
    get attributes() {
        return wrapJoinPoint(this._javaObject.getAttributes());
    }
    get selects() {
        return wrapJoinPoint(this._javaObject.getSelects());
    }
    get actions() {
        return wrapJoinPoint(this._javaObject.getActions());
    }
    def(attribute, value) {
        return wrapJoinPoint(this._javaObject.def(unwrapJoinPoint(attribute), unwrapJoinPoint(value)));
    }
}
/**
 * Type descriptor
 */
export class TypeDescriptor extends Literal {
}
/**
 * Array descriptor
 */
export class ArrayType extends TypeDescriptor {
}
/**
 * Catch directive
 */
export class Catch extends Statement {
    get catch() {
        return wrapJoinPoint(this._javaObject.getCatch());
    }
    get exception() {
        return wrapJoinPoint(this._javaObject.getException());
    }
    get tryEnd() {
        return wrapJoinPoint(this._javaObject.getTryEnd());
    }
    get tryStart() {
        return wrapJoinPoint(this._javaObject.getTryStart());
    }
}
/**
 * Class descriptor
 */
export class ClassType extends TypeDescriptor {
    get className() {
        return wrapJoinPoint(this._javaObject.getClassName());
    }
    get decl() {
        return wrapJoinPoint(this._javaObject.getDecl());
    }
    get packageName() {
        return wrapJoinPoint(this._javaObject.getPackageName());
    }
}
/**
 * Instruction
 */
export class Instruction extends Statement {
    get canThrow() {
        return wrapJoinPoint(this._javaObject.getCanThrow());
    }
    get opCodeName() {
        return wrapJoinPoint(this._javaObject.getOpCodeName());
    }
    get setsRegister() {
        return wrapJoinPoint(this._javaObject.getSetsRegister());
    }
    get setsResult() {
        return wrapJoinPoint(this._javaObject.getSetsResult());
    }
}
/**
 * Label declaration
 */
export class Label extends Statement {
    get name() {
        return wrapJoinPoint(this._javaObject.getName());
    }
}
/**
 * Packed switch directive
 */
export class PackedSwitch extends Statement {
}
/**
 * Primitive descriptor
 */
export class PrimitiveType extends TypeDescriptor {
}
/**
 * Smali instruction formats 10x, 11x
 */
export class ReturnStatement extends Instruction {
}
/**
 * Sparse switch directive
 */
export class SparseSwitch extends Statement {
}
/**
 * Smali instruction format 31t
 */
export class Switch extends Instruction {
}
/**
 * Smali instruction format 11x
 */
export class ThrowStatement extends Instruction {
}
/**
 * Smali instruction formats 10t, 20t, 30t
 */
export class Goto extends Instruction {
    get label() {
        return wrapJoinPoint(this._javaObject.getLabel());
    }
}
/**
 * Smali instruction format 22t
 */
export class IfComparison extends Instruction {
    get label() {
        return wrapJoinPoint(this._javaObject.getLabel());
    }
}
/**
 * Smali instruction format 21t
 */
export class IfComparisonWithZero extends Instruction {
    get label() {
        return wrapJoinPoint(this._javaObject.getLabel());
    }
}
const JoinpointMapper = {
    joinpoint: Joinpoint,
    classNode: ClassNode,
    expression: Expression,
    fieldNode: FieldNode,
    fieldReference: FieldReference,
    labelReference: LabelReference,
    literal: Literal,
    manifest: Manifest,
    methodNode: MethodNode,
    methodPrototype: MethodPrototype,
    methodReference: MethodReference,
    placeholder: Placeholder,
    program: Program,
    registerList: RegisterList,
    registerRange: RegisterRange,
    registerReference: RegisterReference,
    resourceNode: ResourceNode,
    sparseSwitchElement: SparseSwitchElement,
    statement: Statement,
    typeDescriptor: TypeDescriptor,
    arrayType: ArrayType,
    catch: Catch,
    classType: ClassType,
    instruction: Instruction,
    label: Label,
    packedSwitch: PackedSwitch,
    primitiveType: PrimitiveType,
    returnStatement: ReturnStatement,
    sparseSwitch: SparseSwitch,
    switch: Switch,
    throwStatement: ThrowStatement,
    goto: Goto,
    ifComparison: IfComparison,
    ifComparisonWithZero: IfComparisonWithZero,
};
let registered = false;
if (!registered) {
    registerJoinpointMapper(JoinpointMapper);
    registered = true;
}
//# sourceMappingURL=Joinpoints.js.map