///////////////////////////////////////////////////
// This file is generated by build-interfaces.ts //
///////////////////////////////////////////////////

import {
  LaraJoinPoint,
  registerJoinpointMapper,
  wrapJoinPoint,
  unwrapJoinPoint,
  InsertPosition,
} from "@specs-feup/lara/api/LaraJoinPoint.ts";

type PrivateMapper = {
  "Joinpoint": typeof Joinpoint,
  "Placeholder": typeof Placeholder,
  "ResourceNode": typeof ResourceNode,
  "Program": typeof Program,
  "Manifest": typeof Manifest,
  "ClassNode": typeof ClassNode,
  "FieldNode": typeof FieldNode,
  "MethodNode": typeof MethodNode,
  "Expression": typeof Expression,
  "RegisterReference": typeof RegisterReference,
  "LabelReference": typeof LabelReference,
  "MethodReference": typeof MethodReference,
  "FieldReference": typeof FieldReference,
  "SparseSwitchElement": typeof SparseSwitchElement,
  "RegisterList": typeof RegisterList,
  "RegisterRange": typeof RegisterRange,
  "Literal": typeof Literal,
  "PrimitiveLiteral": typeof PrimitiveLiteral,
  "TypeDescriptor": typeof TypeDescriptor,
  "ClassType": typeof ClassType,
  "ArrayType": typeof ArrayType,
  "PrimitiveType": typeof PrimitiveType,
  "MethodPrototype": typeof MethodPrototype,
  "Statement": typeof Statement,
  "LineDirective": typeof LineDirective,
  "Label": typeof Label,
  "Catch": typeof Catch,
  "RegistersDirective": typeof RegistersDirective,
  "Instruction": typeof Instruction,
  "IfComparison": typeof IfComparison,
  "IfComparisonWithZero": typeof IfComparisonWithZero,
  "Goto": typeof Goto,
  "Switch": typeof Switch,
  "SparseSwitch": typeof SparseSwitch,
  "PackedSwitch": typeof PackedSwitch,
  "ReturnStatement": typeof ReturnStatement,
  "ThrowStatement": typeof ThrowStatement,
  "BinaryOp": typeof BinaryOp,
};

type DefaultAttributeMap = {
}

export class Joinpoint extends LaraJoinPoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * String representation of the ast
   */
  get ast(): string { return wrapJoinPoint(this._javaObject.ast()) }
  /**
   * The children of this join point, ignoring null nodes
   */
  get children(): Joinpoint[] { return wrapJoinPoint(this._javaObject.children()) }
  /**
   * All descendants of this join point
   */
  get descendants(): Joinpoint[] { return wrapJoinPoint(this._javaObject.descendants()) }
  /**
   * The id of the node
   */
  get id(): string { return wrapJoinPoint(this._javaObject.id()) }
  /**
   * Returns the parent node in the AST, or undefined if it is the root node
   */
  get parent(): Joinpoint { return wrapJoinPoint(this._javaObject.parent()) }
  /**
   * Returns the 'program' joinpoint
   */
  get root(): Program { return wrapJoinPoint(this._javaObject.root()) }
  /**
   * The scope nodes of this join point
   */
  get scopeNodes(): Joinpoint[] { return wrapJoinPoint(this._javaObject.scopeNodes()) }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  compareNodes(aJoinPoint: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.compareNodes(unwrapJoinPoint(aJoinPoint))); }
  /**
   * Removes the node associated to this joinpoint from the AST
   */
  detach(): Joinpoint { return wrapJoinPoint(this._javaObject.detach()); }
  /**
   * Looks for an ancestor joinpoint name, walking back on the AST
   */
  getAncestor(type: string): Joinpoint { return wrapJoinPoint(this._javaObject.getAncestor(unwrapJoinPoint(type))); }
  /**
   * Returns the child of the node at the given index, ignoring null nodes
   */
  getChild(index: number): Joinpoint { return wrapJoinPoint(this._javaObject.getChild(unwrapJoinPoint(index))); }
  /**
   * Retrieves the descendants of the given type
   */
  getDescendants(type: string): Joinpoint[] { return wrapJoinPoint(this._javaObject.getDescendants(unwrapJoinPoint(type))); }
  /**
   * Retrieves the descendants of the given type, including the node itself
   */
  getDescendantsAndSelf(type: string): Joinpoint[] { return wrapJoinPoint(this._javaObject.getDescendantsAndSelf(unwrapJoinPoint(type))); }
  insert(position: InsertPosition, code: string): Joinpoint[];
  insert(position: InsertPosition, joinpoint: Joinpoint): Joinpoint[];
  insert(p1: InsertPosition, p2: string | Joinpoint): Joinpoint[] { return wrapJoinPoint(this._javaObject.insert(unwrapJoinPoint(p1), unwrapJoinPoint(p2))); }
  /**
   * Inserts the given join point after this join point
   */
  insertAfter(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a string
   */
  insertAfter(code: string): Joinpoint;
  /**
   * Inserts the given join point after this join point
   */
  insertAfter(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertAfter(unwrapJoinPoint(p1))); }
  /**
   * Inserts the given join point before this join point
   */
  insertBefore(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a string
   */
  insertBefore(node: string): Joinpoint;
  /**
   * Inserts the given join point before this join point
   */
  insertBefore(p1: Joinpoint | string): Joinpoint { return wrapJoinPoint(this._javaObject.insertBefore(unwrapJoinPoint(p1))); }
  /**
   * Replaces this node with the given node
   */
  replaceWith(node: Joinpoint): Joinpoint;
  /**
   * Overload which accepts a string
   */
  replaceWith(node: string): Joinpoint;
  /**
   * Overload which accepts a list of join points
   */
  replaceWith(node: Joinpoint[]): Joinpoint;
  /**
   * Replaces this node with the given node
   */
  replaceWith(p1: Joinpoint | string | Joinpoint[]): Joinpoint { return wrapJoinPoint(this._javaObject.replaceWith(unwrapJoinPoint(p1))); }
  /**
   * Overload which accepts a list of strings
   */
  replaceWithStrings(node: string[]): Joinpoint { return wrapJoinPoint(this._javaObject.replaceWithStrings(unwrapJoinPoint(node))); }
  /**
   * Compares this join point with another join point for identity (i.e., whether they represent the same AST node)
   */
  same(other: Joinpoint): boolean { return wrapJoinPoint(this._javaObject.same(unwrapJoinPoint(other))); }
}

  /**
   * Placeholder node
   */
export class Placeholder extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get kind(): string { return wrapJoinPoint(this._javaObject.kind()) }
}

  /**
   * Resource nodes, like xml files are not being handled for now
   */
export class ResourceNode extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * App node
   */
export class Program extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get classes(): ClassNode[] { return wrapJoinPoint(this._javaObject.classes()) }
  get manifest(): Manifest { return wrapJoinPoint(this._javaObject.manifest()) }
  buildApk(outputName: string): void { return wrapJoinPoint(this._javaObject.buildApk(unwrapJoinPoint(outputName))); }
}

  /**
   * The application's manifest
   */
export class Manifest extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get activities(): string[] { return wrapJoinPoint(this._javaObject.activities()) }
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
  get services(): string[] { return wrapJoinPoint(this._javaObject.services()) }
}

  /**
   * Class definition
   */
export class ClassNode extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get classDescriptor(): ClassType { return wrapJoinPoint(this._javaObject.classDescriptor()) }
  get fields(): FieldNode[] { return wrapJoinPoint(this._javaObject.fields()) }
  get methods(): MethodNode[] { return wrapJoinPoint(this._javaObject.methods()) }
  get superClassDescriptor(): ClassType { return wrapJoinPoint(this._javaObject.superClassDescriptor()) }
}

  /**
   * Field definition
   */
export class FieldNode extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get isStatic(): boolean { return wrapJoinPoint(this._javaObject.isStatic()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get referenceName(): string { return wrapJoinPoint(this._javaObject.referenceName()) }
}

  /**
   * Method definition
   */
export class MethodNode extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get isStatic(): boolean { return wrapJoinPoint(this._javaObject.isStatic()) }
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get prototype(): MethodPrototype { return wrapJoinPoint(this._javaObject.prototype()) }
  get referenceName(): string { return wrapJoinPoint(this._javaObject.referenceName()) }
  get registersDirective(): RegistersDirective { return wrapJoinPoint(this._javaObject.registersDirective()) }
}

  /**
   * Expression
   */
export class Expression extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Register reference
   */
export class RegisterReference extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Label reference
   */
export class LabelReference extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get decl(): Label { return wrapJoinPoint(this._javaObject.decl()) }
}

  /**
   * Method reference
   */
export class MethodReference extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
  get parentClassDescriptor(): TypeDescriptor { return wrapJoinPoint(this._javaObject.parentClassDescriptor()) }
  get prototype(): MethodPrototype { return wrapJoinPoint(this._javaObject.prototype()) }
}

  /**
   * Field reference
   */
export class FieldReference extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Sparse switch element
   */
export class SparseSwitchElement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get label(): LabelReference { return wrapJoinPoint(this._javaObject.label()) }
}

  /**
   * Register list
   */
export class RegisterList extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Register range
   */
export class RegisterRange extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Literal
   */
export class Literal extends Expression {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Primitive literal
   */
export class PrimitiveLiteral extends Literal {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  setValue(value: string): string { return wrapJoinPoint(this._javaObject.setValue(unwrapJoinPoint(value))); }
}

  /**
   * Type descriptor
   */
export class TypeDescriptor extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Class descriptor
   */
export class ClassType extends TypeDescriptor {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get className(): string { return wrapJoinPoint(this._javaObject.className()) }
  get decl(): ClassNode { return wrapJoinPoint(this._javaObject.decl()) }
  get packageName(): string { return wrapJoinPoint(this._javaObject.packageName()) }
}

  /**
   * Array descriptor
   */
export class ArrayType extends TypeDescriptor {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Primitive descriptor
   */
export class PrimitiveType extends TypeDescriptor {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Method prototype
   */
export class MethodPrototype extends TypeDescriptor {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get parameters(): TypeDescriptor[] { return wrapJoinPoint(this._javaObject.parameters()) }
  get returnType(): TypeDescriptor { return wrapJoinPoint(this._javaObject.returnType()) }
}

  /**
   * Statement
   */
export class Statement extends Joinpoint {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get nextStatement(): Statement { return wrapJoinPoint(this._javaObject.nextStatement()) }
  get prevStatement(): Statement { return wrapJoinPoint(this._javaObject.prevStatement()) }
}

  /**
   * Line directive
   */
export class LineDirective extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get value(): number { return wrapJoinPoint(this._javaObject.value()) }
}

  /**
   * Label declaration
   */
export class Label extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get name(): string { return wrapJoinPoint(this._javaObject.name()) }
}

  /**
   * Catch directive
   */
export class Catch extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get catch(): LabelReference { return wrapJoinPoint(this._javaObject._catch()) }
  get exception(): TypeDescriptor { return wrapJoinPoint(this._javaObject.exception()) }
  get tryEnd(): LabelReference { return wrapJoinPoint(this._javaObject.tryEnd()) }
  get tryStart(): LabelReference { return wrapJoinPoint(this._javaObject.tryStart()) }
}

  /**
   * Registers directive
   */
export class RegistersDirective extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get type(): string { return wrapJoinPoint(this._javaObject.type()) }
  get value(): number { return wrapJoinPoint(this._javaObject.value()) }
}

  /**
   * Instruction
   */
export class Instruction extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get canThrow(): boolean { return wrapJoinPoint(this._javaObject.canThrow()) }
  get opCodeName(): string { return wrapJoinPoint(this._javaObject.opCodeName()) }
  get setsRegister(): boolean { return wrapJoinPoint(this._javaObject.setsRegister()) }
  get setsResult(): boolean { return wrapJoinPoint(this._javaObject.setsResult()) }
}

  /**
   * Smali instruction format 22t
   */
export class IfComparison extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get label(): LabelReference { return wrapJoinPoint(this._javaObject.label()) }
}

  /**
   * Smali instruction format 21t
   */
export class IfComparisonWithZero extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get label(): LabelReference { return wrapJoinPoint(this._javaObject.label()) }
}

  /**
   * Smali instruction formats 10t, 20t, 30t
   */
export class Goto extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  get label(): LabelReference { return wrapJoinPoint(this._javaObject.label()) }
}

  /**
   * Smali instruction format 31t
   */
export class Switch extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Sparse switch directive
   */
export class SparseSwitch extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Packed switch directive
   */
export class PackedSwitch extends Statement {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Smali instruction formats 10x, 11x
   */
export class ReturnStatement extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Smali instruction format 11x
   */
export class ThrowStatement extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
}

  /**
   * Smali instruction formats 12x, 22b, 22s, 23x
   */
export class BinaryOp extends Instruction {
  /**
   * @internal
   */
  static readonly _defaultAttributeInfo: {readonly map?: DefaultAttributeMap, readonly name: string | null, readonly type?: PrivateMapper, readonly jpMapper?: typeof JoinpointMapper} = {
    name: null,
  };
  /**
   * Sets the operator of this instruction
   */
  setOperator(operation: string): void { return wrapJoinPoint(this._javaObject.setOperator(unwrapJoinPoint(operation))); }
}

const JoinpointMapper = {
  joinpoint: Joinpoint,
  placeholder: Placeholder,
  resourceNode: ResourceNode,
  program: Program,
  manifest: Manifest,
  classNode: ClassNode,
  fieldNode: FieldNode,
  methodNode: MethodNode,
  expression: Expression,
  registerReference: RegisterReference,
  labelReference: LabelReference,
  methodReference: MethodReference,
  fieldReference: FieldReference,
  sparseSwitchElement: SparseSwitchElement,
  registerList: RegisterList,
  registerRange: RegisterRange,
  literal: Literal,
  primitiveLiteral: PrimitiveLiteral,
  typeDescriptor: TypeDescriptor,
  classType: ClassType,
  arrayType: ArrayType,
  primitiveType: PrimitiveType,
  methodPrototype: MethodPrototype,
  statement: Statement,
  lineDirective: LineDirective,
  label: Label,
  catch: Catch,
  registersDirective: RegistersDirective,
  instruction: Instruction,
  ifComparison: IfComparison,
  ifComparisonWithZero: IfComparisonWithZero,
  goto: Goto,
  switch: Switch,
  sparseSwitch: SparseSwitch,
  packedSwitch: PackedSwitch,
  returnStatement: ReturnStatement,
  throwStatement: ThrowStatement,
  binaryOp: BinaryOp,
};

let registered = false;
if (!registered) {
  registerJoinpointMapper(JoinpointMapper);
  registered = true;
}

